### ISSUE TITLE
Explorer opens to directory, not filename

### ISSUE THREAD

**Issue by maryandmike** [skycommand/AdminScripts#4]
So, script works fine, except...

When I run it and select 'yes', it opens the explorer, but only opens to the directory and doesn't select the actual photo.

Then if I run this script on a separate line, it shows the directory and selects the photo as intended.

                 Start-Process explorer.exe -ArgumentList "/select,`"$WallpaperSource`""

My explorer.exe shows thumbnails as default.

Hope this helps...

Windows11, latest preview build 22H2 22623.1095

**Comment by skycommand** [comment]
I can't reproduce your report. The script runs as intended here. I don't use a beta build of Microsoft Windows, though. They are supposed to have bugs.
